version: '3'
services:
  frontend:
    build: .
    image: wb-frontend
    container_name: wb-frontend
    stdin_open: true
    tty: true
    ports:
      - "8080:8080"
    volumes:
      - ./:/var/www/html/wb-frontend